### ISSUE TITLE
Management of multiple templates feature

### ISSUE THREAD

**Issue by kervincort225** [Ignaciojeria/einar-cli#11]
an error is encountered when using two templates. 
example:

a corporate template is used and when using the public template, the code of the corporate template is still taken.

**Comment by Ignaciojeria** [comment]
multiple template selection is in progress as a new feature. pull request coming soon.

**Comment by Ignaciojeria** [comment]
feature merged into master : https://github.com/Ignaciojeria/einar/pull/12/files

**Comment by Ignaciojeria** [comment]
Please install the latest version using the following command: 'go install github.com/Ignaciojeria/einar@v1.20.0'. Let me know if this works for your specific use case, so we can update the documentation accordingly.

**Comment by Ignaciojeria** [comment]
resolved in the latest version
